# Generated by Django 3.0.1 on 2019-12-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('end_date', models.DateTimeField()),
                ('project_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarningNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pass_project_due_date', 'Proyektin müddətindən keçmişdir'), ('proyekt_due_date_last', 'Proyekt müddətinin son gunu ')], max_length=50)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_notification', to='core.Projects')),
            ],
            options={
                'verbose_name': 'Warning Notification',
                'verbose_name_plural': 'Warning Notifications',
            },
        ),
        migrations.CreateModel(
            name='InfoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_due_date_ten', 'Proyektin müddətinə 10 gün qalır'), ('project_due_date_five', 'Proyektin müddətinə 5 gün qalır')], max_length=50)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_notification', to='core.Projects')),
            ],
            options={
                'verbose_name': 'Info Notification',
                'verbose_name_plural': 'Info Notifications',
            },
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Projects')),
            ],
        ),
    ]
