# Generated by Django 3.0.1 on 2019-12-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pass_project_due_date', 'Proyektin müddətindən keçmişdir'), ('proyekt_due_date_last', 'Proyekt müddətinin son gunu ')], max_length=50)),
                ('read_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scroller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_notification', to='core.Projects')),
            ],
            options={
                'verbose_name': 'Warning Notification',
                'verbose_name_plural': 'Warning Notifications',
            },
        ),
        migrations.CreateModel(
            name='InfoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_due_date_ten', 'Proyektin müddəti  yaxınlaşır'), ('project_due_date_five', 'Proyektin müddəti  yaxınlaşır')], max_length=50)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_notification', to='core.Projects')),
            ],
            options={
                'verbose_name': 'Info Notification',
                'verbose_name_plural': 'Info Notifications',
            },
        ),
    ]
