# Generated by Django 3.0.1 on 2019-12-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_warningnotifications_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='infonotifications',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
