# Generated by Django 3.0.1 on 2019-12-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191223_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warningnotifications',
            old_name='scroller_name',
            new_name='project_name',
        ),
    ]
