# Generated by Django 3.0.1 on 2019-12-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191223_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_bool',
            field=models.BooleanField(default=False),
        ),
    ]
