# Generated by Django 3.0.1 on 2019-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projects_project_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonotifications',
            name='notification_type',
            field=models.CharField(choices=[('project_due_date_ten', 'Proyektin müddətinə 10 gün qalır'), ('project_due_date_five', 'Proyektin müddətinə 5 gün qalır')], max_length=50),
        ),
    ]
